package edu.thi.constants.enums;

public enum Status {
	EINGEGANGEN,
	INPRUEFUNG,
	UMSETZBAR,
	EINGESCHRAENKTUMSETZBAR,
	NICHTUMSETZBAR,
	GENEHMIGT,
	ABGELEHNT,
	INBEARBEITUNG,
	TERMINVEREINBART,
	ABGESCHLOSSEN,
	NICHTERFOLGREICH;
}
